# Generated by Django 4.1.5 on 2023-01-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='hora',
        ),
        migrations.AddField(
            model_name='aula',
            name='detalhes',
            field=models.TextField(default=' detalhes da aula'),
            preserve_default=False,
        ),
    ]
