# Generated by Django 4.1.5 on 2023-01-09 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_remove_aula_detalhes_alter_aula_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
